### ISSUE TITLE
Cut a 0.0.1 release of ocicrypt-rs

### ISSUE THREAD

**Issue by fidencio** [confidential-containers/ocicrypt-rs#27]
ocicrypt-rs is currently being used as part of the image-rs.  However, we're importing `main` there, and this is very much error prone and not suitable for the moment when we start working on reproducible builds (a hard requirement for Confidential Containers).

With this in mind, please, let's cut a 0.0.1 release with a commit that's known to be working, and we can use that as part of image-rs.

Image-rs link: https://github.com/confidential-containers/image-rs/blob/00ea90d5151025b02f84350d2b31394636cb4ede/Cargo.toml#L19

**Comment by fidencio** [comment]
Another option, if a release is not yet welcome, would be pinning a specific commit of ocicrypt-rs as part of image-rs.

**Comment by lumjjb** [comment]
Wondering if we should come up with some consistency between the golang and
rs versions. Just cause they share common apis, like the provider API.

Maybe keeping the minor version across for api consistency and only bumping
that when necessary? Thoughts?

**Comment by fidencio** [comment]
Hmm.  Not sure what's less confusing for consumers.

Having it with the same version as golang, or having a table on the README saying v0.0.1 is based on golang version vx.y.z.
I'd go for the latter as that gives more flexibility to do bumps in this project.

**Comment by fidencio** [comment]
Right now we're pinning a specific commit of ocicrypt-rs in the image-rs, and I'm closing it now.
